export const SET_BLOCK_HEIGHT = 'SET_BLOCK_HEIGHT';
export const SET_SEARCH_INFO = 'SET_SEARCH_INFO';
export const SET_RUN_STATUS = 'SET_RUN_STATUS';
export const SET_ONT_ID_LIST = 'SET_ONT_ID_LIST';
export const SET_ONT_ID_LIST_PAGE = 'SET_ONT_ID_LIST_PAGE';
export const SET_ONT_ID_DETAIL_PAGE = 'SET_ONT_ID_DETAIL_PAGE';
export const SET_BLOCK_LIST = 'SET_BLOCK_LIST';
export const SET_BLOCK_LIST_PAGE = 'SET_BLOCK_LIST_PAGE';
export const SET_BLOCK_DETAIL_PAGE = 'SET_BLOCK_DETAIL_PAGE';
export const SET_TRANSACTION_LIST = 'SET_TRANSACTIOM_LIST';
export const SET_TRANSACTION_LIST_PAGE = 'SET_TRANSACTION_LIST_PAGE';
export const SET_TRANSACTION_DETAIL_PAGE = 'SET_TRANSACTION_DETAIL_PAGE';
export const SET_GENERATE_TIME = 'SET_GENERATE_TIME';
export const SET_ADDRESS_DETAIL_PAGE = 'SET_ADDRESS_DETAIL_PAGE';
export const SET_ADDRESS_LIST_PAGE = 'SET_ADDRESS_LIST_PAGE';
export const GET_CLAIM = 'GET_CLAIM';

export const UPDATE_NODE_LIST = 'UPDATE_NODE_LIST';
export const UPDATE_COUNTDOWN_BLOCK = 'UPDATE_COUNTDOWN_BLOCK';
export const UPDATE_NODE_INFO = 'UPDATE_NODE_INFO';
export const UPDATE_FETCH_PROCESS = 'UPDATE_FETCH_PROCESS';

export const SET_CONTRACTS_DATA = 'SET_CONTRACTS_DATA';
export const SET_CONTRACT_DATA = 'SET_CONTRACT_DATA';

export const SET_TOKENS_DATA = 'SET_TOKENS_DATA';
export const SET_TOKEN_DATA = 'SET_TOKEN_DATA';

export const SET_STATISTICS_DATA = 'SET_STATISTICS_DATA';
export const SET_SC_LIST = 'SET_SC_LIST';
